# Generated by Django 4.1.4 on 2023-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
