# Generated by Django 4.1.4 on 2024-01-23 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_blog_thumbnail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaDeVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='hojas_de_vida/')),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
