# Generated by Django 4.1.4 on 2024-01-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hojadevida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hojadevida',
            name='archivo_pdf',
            field=models.FileField(default='hoja_de_vida.pdf', upload_to='hojas_de_vida/'),
        ),
    ]
